### ISSUE TITLE
Error during learning

### ISSUE THREAD

**Issue by alecive** [ScazLab/rpi_integration#3]
Now the travis integration works. I only have one last problem (@drjesseenglish feel free to address it on monday though): as you can see here https://travis-ci.org/ScazLab/rpi_integration/builds/377850171 , the two `curl` requests that I added just to test the infrastructure work, but when I asked this request:

```curl -v -s -H "Content-type: application/json" -X POST -d '[["u", "We will build a chair."], ["a", "get-screwdriver"]]' http://0.0.0.0:5002/learn```

The output is the correct json file, with some error too:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/backend/main.py", line 82, in learn
    tmrs = input_to_tmrs(data)
  File "/app/backend/utils/YaleUtils.py", line 86, in input_to_tmrs
    tmrs.append(analyze(input[i][1]))
  File "/app/backend/utils/YaleUtils.py", line 117, in analyze
    return json.loads(response.text)[0]
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
{
    "nodes": {
        "id": 1,
        "parent": null,
        "name": "BUILD CHAIR",
        "combination": "Sequential",
        "attributes": [],
        "children": [
            {
                "id": 2,
                "parent": 1,
                "name": "ROBOT GET(screwdriver)",
                "combination": "Sequential",
                "attributes": [],
                "children": []
            }
        ]
    }
}
```

Any advice?

**Comment by alecive** [comment]
Hell yeah! Sleeping 60 seconds fixed the issue : https://travis-ci.org/ScazLab/rpi_integration/builds/378740724
